/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Media = {
  type?: "image" | "video";
  image?: MediaImage;
  video?: Video;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type MediaImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  _type: "image";
};

export type Video = {
  file?: MuxVideo;
  description?: string;
};

export type SeoImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "seoImage.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type FaqMedia = {
  type?: "image" | "video";
  image?: FaqMediaImage;
  video?: MediaVideo;
};

export type FaqMediaImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  _type: "image";
};

export type MediaVideo = {
  file?: MuxVideo;
  description?: string;
};

export type PageTypeOneReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pageTypeOne";
};

export type PageTypeTwoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pageTypeTwo";
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceType?: "internal" | "custom";
  sourcePage?: PageTypeOneReference | PageTypeTwoReference;
  sourcePath?: string;
  destinationType?: "internal" | "custom";
  destinationPage?: PageTypeOneReference | PageTypeTwoReference;
  destinationPath?: string;
  permanent?: boolean;
};

export type HomepageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homepage";
};

export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: RichText;
  internalTitle?: string;
  seoTitle?: string;
  slugMode?: "default" | "parentPage";
  parentPage?: HomepageReference | PageTypeOneReference | PageTypeTwoReference;
  seoDescription?: string;
  seoImage?: SeoImage;
  noIndex?: boolean;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  footerNav?: Array<
    {
      _key: string;
    } & NavItem
  >;
  copyrightText?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainNav?: Array<
    {
      _key: string;
    } & NavItem
  >;
};

export type NavItemL3 = {
  _type: "navItemL3";
  label?: string;
  linkType?: "internal" | "external";
  internalPage?:
    | HomepageReference
    | PageTypeOneReference
    | PageTypeTwoReference;
  externalUrl?: string;
  openInNewWindow?: boolean;
};

export type NavItemL2 = {
  _type: "navItemL2";
  label?: string;
  hasSubmenu?: boolean;
  linkType?: "internal" | "external";
  internalPage?:
    | HomepageReference
    | PageTypeOneReference
    | PageTypeTwoReference;
  externalUrl?: string;
  openInNewWindow?: boolean;
  children?: Array<
    {
      _key: string;
    } & NavItemL3
  >;
};

export type NavItem = {
  _type: "navItem";
  label?: string;
  hasSubmenu?: boolean;
  linkType?: "internal" | "external";
  internalPage?:
    | HomepageReference
    | PageTypeOneReference
    | PageTypeTwoReference;
  externalUrl?: string;
  openInNewWindow?: boolean;
  children?: Array<
    {
      _key: string;
    } & NavItemL2
  >;
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  internalPage?:
    | HomepageReference
    | PageTypeOneReference
    | PageTypeTwoReference;
  externalUrl?: string;
  openInNewWindow?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type PlainRichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PageTypeOne = {
  _id: string;
  _type: "pageTypeOne";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  components?: Array<
    {
      _key: string;
    } & Hero
  >;
  internalTitle?: string;
  seoTitle?: string;
  slugMode?: "default" | "parentPage";
  parentPage?: HomepageReference | PageTypeOneReference | PageTypeTwoReference;
  slug?: Slug;
  seoDescription?: string;
  seoImage?: SeoImage;
  noIndex?: boolean;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  components?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Faq)
  >;
  internalTitle?: string;
  seoTitle?: string;
  slugMode?: "default" | "parentPage";
  parentPage?: HomepageReference | PageTypeOneReference | PageTypeTwoReference;
  seoDescription?: string;
  seoImage?: SeoImage;
  noIndex?: boolean;
};

export type PageTypeTwo = {
  _id: string;
  _type: "pageTypeTwo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  components?: Array<
    {
      _key: string;
    } & Hero
  >;
  internalTitle?: string;
  seoTitle?: string;
  slugMode?: "default" | "parentPage";
  parentPage?: HomepageReference | PageTypeOneReference | PageTypeTwoReference;
  slug?: Slug;
  seoDescription?: string;
  seoImage?: SeoImage;
  noIndex?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Hero = {
  _type: "hero";
  title?: string;
  media?: Media;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type Faq = {
  _type: "faq";
  title?: string;
  media?: FaqMedia;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Media
  | SanityImageAssetReference
  | MediaImage
  | Video
  | SeoImage
  | FaqMedia
  | FaqMediaImage
  | MediaVideo
  | PageTypeOneReference
  | PageTypeTwoReference
  | Redirect
  | HomepageReference
  | NotFoundPage
  | RichText
  | Footer
  | Navigation
  | NavItemL3
  | NavItemL2
  | NavItem
  | Link
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | PlainRichText
  | PageTypeOne
  | Homepage
  | PageTypeTwo
  | Slug
  | Hero
  | MuxVideoAssetReference
  | MuxVideo
  | Faq
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
